version: '3.8'

services:
  react-app:
    image: node:20-alpine
    container_name: front-geoBoost-react
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: sh -c "cd app && npm install && npm run start"
    networks:
      - app-network

#  nginx:
#    image: nginx:alpine
#    container_name: front-geoBoost-nginx
#    volumes:
#      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
#      - ./app:/usr/share/nginx/html
#    ports:
#      - "80:80"
#    networks:
#      - app-network

networks:
  app-network:
    external: true